version: "3.8"

services:
  db:
    image: mariadb
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=php
    ports:
      #local : docker
      - 3306:3306
    volumes:
      - ./db_data:/etc/mysql/conf.d

  app:
    image: weslen/webserver:1.0
    volumes:
      #local :  docker
      - ./:/var/www/html
    ports:
      #local : docker
      - 80:80
    links:
      - db
    depends_on:
      - db
    tty: true